<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rs</string>
		<string>rc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\bfn\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Rust</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.source.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rust_escaped_character</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.rust</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rust_escaped_character</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.rust</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>functions with types</string>
			<key>match</key>
			<string>\b(fn)\s+([a-zA-Z_]\w*)\s*(\()</string>
			<key>name</key>
			<string>meta.function.source.rust</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.source.rust</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.rust</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>functions without types</string>
			<key>match</key>
			<string>\b(fn)\s+([a-zA-Z_]\w*)\s*(\()</string>
			<key>name</key>
			<string>meta.function.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(again|as|break|check|claim|const|copy|do|drop|else|export|extern|fail|for|if|impl|import|in|let|log|loop|match|mod|module|move|mut|new|of|owned|priv|pub|pure|return|to|unchecked|use|while|with|mod|trait|class|struct|enum|type)\b</string>
			<key>name</key>
			<string>keyword.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(m32|m64|m128|f80|f16|f128|int|uint|float|char|bool|u8|u16|u32|u64|f32|f64|i8|i16|i32|i64|str|option|either|c_float|c_double|c_void|FILE|fpos_t|DIR|dirent|c_char|c_schar|c_uchar|c_short|c_ushort|c_int|c_uint|c_long|c_ulong|size_t|ptrdiff_t|clock_t|time_t|c_longlong|c_ulonglong|intptr_t|uintptr_t|off_t|dev_t|ino_t|pid_t|mode_t|ssize_t)\b</string>
			<key>name</key>
			<string>storage.type.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bself\b</string>
			<key>name</key>
			<string>variable.language.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|some|none|left|right|ok|err|success|failure|cons|nil|empty|node)\b</string>
			<key>name</key>
			<string>constant.language.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(EXIT_FAILURE|EXIT_SUCCESS|RAND_MAX|EOF|SEEK_SET|SEEK_CUR|SEEK_END|_IOFBF|_IONBF|_IOLBF|BUFSIZ|FOPEN_MAX|FILENAME_MAX|L_tmpnam|TMP_MAX|O_RDONLY|O_WRONLY|O_RDWR|O_APPEND|O_CREAT|O_EXCL|O_TRUNC|S_IFIFO|S_IFCHR|S_IFBLK|S_IFDIR|S_IFREG|S_IFMT|S_IEXEC|S_IWRITE|S_IREAD|S_IRWXU|S_IXUSR|S_IWUSR|S_IRUSR|F_OK|R_OK|W_OK|X_OK|STDIN_FILENO|STDOUT_FILENO|STDERR_FILENO)\b</string>
			<key>name</key>
			<string>support.constant.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\w\(\w\)*!)|(#\[[\w=\(\)_]+\])\b</string>
			<key>name</key>
			<string>meta.preprocessor.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9][0-9_]*)|([0-9][0-9_]*(u|u8|u16|u32|u64))|([0-9][0-9_]*(i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.integer.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0x[a-fA-F0-9_]+)|(0x[a-fA-F0-9_]+(u|u8|u16|u32|u64))|(0x[a-fA-F0-9_]+(i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.hex.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0b[01_]+)|(0b[01_]+(u|u8|u16|u32|u64))|(0b[01_]+(i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.binary.source.rust</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9][0-9_]*(f|f32|f64))|([0-9][0-9_]*([eE][+-]=[0-9_]+))|([0-9][0-9_]*([eE][+-]=[0-9_]+)(f|f32|f64))|([0-9][0-9_]*\.[0-9_]+)|([0-9][0-9_]*\.[0-9_]+(f|f32|f64))|([0-9][0-9_]*\.[0-9_]+%([eE][+-]=[0-9_]+))|([0-9][0-9_]*\.[0-9_]+%([eE][+-]=[0-9_]+)(f|f32|f64))</string>
			<key>name</key>
			<string>constant.numeric.float.source.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//!</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.documentation.source.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.double-dash.source.rust</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.rust</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>rust_escaped_character</key>
		<dict>
			<key>match</key>
			<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
			<key>name</key>
			<string>constant.character.escape.source.rust</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rust</string>
	<key>uuid</key>
	<string>4339386b-4d67-4f0e-9e78-09ecbcddf71d</string>
</dict>
</plist>
